config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :farms, shallow: true, only: %w[index show new create] do
    resources :harvests, only: %w[index show new create] do
      resources :events, only: %w[new create]
      member do
        get 'finish'
        post 'finished'
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.attributes.\
#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  validates :text, :date, presence: true

  belongs_to :harvest
  belongs_to :user
end

app/models/farm.rb
# frozen_string_literal: true

class Farm < ApplicationRecord
  validates :name, :address, :size, :latitude, :longitude, presence: true

  belongs_to :user
  has_many :harvests, dependent: :nullify

  def active_harvest
    harvests.where(state: 'active').last.try(:decorate)
  end
end

app/models/harvest.rb
# frozen_string_literal: true

class Harvest < ApplicationRecord
  validates :seed, :initial_date, :state,
            :end_date_prediction, :employee, presence: true

  validates :final_notes, :state, :total_collected,
            presence: true, unless: :new_record?

  validate :older_active_harvest

  belongs_to :farm
  belongs_to :user
  has_many :events, dependent: :nullify

  enum state: %i[active cancelled ended]

  scope :older, lambda { |harvest|
    where(seed: harvest.seed, farm: harvest.farm)
      .where('created_at < ?', harvest.created_at)
  }

  def older_active_harvest
    return unless farm.active_harvest.try(:active?) &&
                  farm.active_harvest.id != id
    errors.add(:seed, :has_other_active_farm)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :farms, dependent: :nullify
  has_many :harvests, dependent: :nullify
  has_many :events, dependent: :nullify
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def validate_user(obj)
    return if obj.user == current_user
    flash[:alert] = I18n.t('alerts.user_denied', page: obj.model_name.human)
    redirect_to root_path
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_harvest, only: %i[new create]

  def new
    @event = Event.new
  end

  def create
    @event = @harvest.events.new(event_params)
    @event.user = current_user
    if @event.save
      redirect_to harvest_path(@event.harvest)
    else
      render :new
    end
  end

  private

  def set_harvest
    @harvest = Harvest.find(params[:harvest_id])
  end

  def event_params
    params.require(:event).permit(:text, :date)
  end
end

app/controllers/farms_controller.rb
# frozen_string_literal: true

class FarmsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_farm, only: [:show]
  before_action -> { validate_user(@farm) }, only: [:show]

  def show; end

  def index
    @farms = current_user.farms
  end

  def new
    @farm = Farm.new
  end

  def create
    @farm = Farm.new(farm_params)
    @farm.user = current_user
    if @farm.save
      redirect_to @farm
    else
      render :new
    end
  end

  private

  def set_farm
    @farm = Farm.find(params[:id])
  end

  def farm_params
    params.require(:farm).permit(:name, :address, :size, :latitude, :longitude)
  end
end

app/controllers/harvests_controller.rb
# frozen_string_literal: true

class HarvestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_farm, only: %i[index new create]
  before_action :set_harvest, only: %i[show finish finished]
  before_action -> { validate_user(@harvest) }, only: [:show]

  def index
    @harvests = @farm.harvests.decorate
  end

  def show; end

  def new
    @harvest = Harvest.new
  end

  def create
    @harvest = @farm.harvests.build(harvest_params)
    @harvest.user = current_user
    if @harvest.save
      redirect_to harvest_path(@harvest)
    else
      render :new
    end
  end

  def finish; end

  def finished
    if @harvest.update(harvest_finish_params)
      redirect_to harvest_path(@harvest)
    else
      render :finish
    end
  end

  private

  def set_harvest
    @harvest = Harvest.find(params[:id]).decorate
  end

  def set_farm
    @farm = Farm.find(params[:farm_id])
  end

  def harvest_finish_params
    params.require(:harvest).permit(:final_notes, :state, :total_collected)
  end

  def harvest_params
    params.require(:harvest).permit(:seed, :initial_date, :end_date_prediction,
                                    :employee, :state)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/events/new.html.erb
<%= simple_form_for [@harvest, @event] do |f| %>
  <%= f.input :text %>
  <%= f.input :date, as: :date, html5: true %>
  <%= f.button :submit %>
<% end %>

app/views/farms/_farm.html.erb
<h2><%= link_to farm.name, farm_path(farm) %></h2>

<dl>
  <dt><%= Farm.human_attribute_name(:address) %></dt>
  <dd><%= farm.address %></dd>
  <dt><%= Farm.human_attribute_name(:size) %></dt>
  <dd><%= farm.size %></dd>
  <dt><%= Farm.human_attribute_name(:latitude) %></dt>
  <dd><%= farm.latitude %></dd>
  <dt><%= Farm.human_attribute_name(:longitude) %></dt>
  <dd><%= farm.longitude %></dd>
</dl>

app/views/farms/index.html.erb
<% @farms.each do |farm| %>
  <%= render farm %>
  <hr>
<% end %>

app/views/farms/new.html.erb
<%= simple_form_for @farm do |f| %>
  <legend><%= t('.creating_farm') %></legend>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :size %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
  <%= f.button :submit %>
<% end %>

app/views/farms/show.html.erb
<h1><%= @farm.name %></h1>
<hr>

<div class="row">
  <div class="col-4">
    <dl>
      <dt><%= Farm.human_attribute_name(:address) %></dt>
      <dd><%= @farm.address %></dd>
      <dt><%= Farm.human_attribute_name(:size) %></dt>
      <dd><%= @farm.size %></dd>
      <dt><%= Farm.human_attribute_name(:latitude) %></dt>
      <dd><%= @farm.latitude %></dd>
      <dt><%= Farm.human_attribute_name(:longitude) %></dt>
      <dd><%= @farm.longitude %></dd>
    </dl>

    <%= link_to t('.register_harvest'), new_farm_harvest_path(@farm), class: 'btn btn-success' unless @farm.active_harvest.present? %>
    <%= link_to t('.all_harvests'), farm_harvests_path(@farm), class: 'btn btn-info' %>
  </div>

  <div class="col">
    <%= render @farm.active_harvest if @farm.active_harvest.present? %>
  </div>
</div>

app/views/harvests/_harvest.html.erb
<h1><%= link_to harvest.title, harvest_path(harvest) %></h1>

<dl>
  <dt><%= Harvest.human_attribute_name(:seed) %><dt>
  <dd><%= harvest.seed %></dd>

  <dt><%= Harvest.human_attribute_name(:initial_date) %><dt>
  <dd><%= l harvest.initial_date %></dd>

  <dt><%= Harvest.human_attribute_name(:end_date_prediction) %><dt>
  <dd><%= l harvest.end_date_prediction %></dd>

  <dt><%= Harvest.human_attribute_name(:employee) %></dt>
  <dd><%= harvest.employee %></dd>

  <dt><%= Harvest.human_attribute_name(:farm) %></dt>
  <dd><%= link_to harvest.farm.name, farm_path(harvest.farm) %></dd>

  <dt><%= Harvest.human_attribute_name(:state) %></dt>
  <dd><%= Harvest.human_enum_name(:state, harvest.state.to_sym) %></dd>

  <dt><%= Harvest.human_attribute_name(:events) %></dt>
  <dd>
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col"><%= Event.human_attribute_name(:date) %></th>
          <th scope="col"><%= Event.human_attribute_name(:text) %></th>
        </tr>
      </thead>
      <tbody>
        <% harvest.events.each do |event| %>
          <tr>
            <th scope='row'><%= I18n.l(event.date) %></th>
            <td><%= event.text %></th>
          </tr>
        <% end %>
      </tbody>
    </table>
  </dd>

  <% unless harvest.active? %>
    <dt><%= Harvest.human_attribute_name(:total_collected) %></dt>
    <dd><%= harvest.total_collected %></dd>

    <dt><%= Harvest.human_attribute_name(:final_notes) %></dt>
    <dd><%= harvest.final_notes %></dd>
  <% end %>
</dl>

<% if harvest.active? %>
  <%= link_to t('.add_event'), new_harvest_event_path(harvest), class: 'btn btn-primary' %>
  <%= link_to t('.end_harvest'), finish_harvest_path(harvest), class: 'btn btn-danger' %>
<% end %>

app/views/harvests/finish.html.erb
<%= simple_form_for @harvest, method: :post, url: finished_harvest_path do |f| %>
  <%= f.input :state, collection: [[Harvest.human_enum_name(:state, :cancelled), 'cancelled'], [Harvest.human_enum_name(:state, :ended), 'ended']] %>
  <%= f.input :total_collected %>
  <%= f.input :final_notes %>
  <%= f.button :submit, t('.finish') %>
<% end %>

app/views/harvests/index.html.erb
<% @harvests.each do |harvest| %>
  <%= render harvest %>
  <hr>
<% end %>

app/views/harvests/new.html.erb
<%= simple_form_for [@farm, @harvest] do |f| %>
  <%= f.hidden_field :state, value: 'active' %>
  <%= f.input :seed %>
  <%= f.input :initial_date, as: :date, html5: true %>
  <%= f.input :end_date_prediction, as: :date, html5: true %>
  <%= f.input :employee %>
  <%= f.button :submit %>
<% end %>

app/views/harvests/show.html.erb
<%= render @harvest %>

app/views/home/index.html.erb
<h1>Coltivazione</h1>

<%= link_to t('.create_farm'), new_farm_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coltivazione</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Coltivazione', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to Farm.model_name.human.pluralize, farms_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item active">
              <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <% if notice %>
      <div class="alert alert-info" role="alert">
        <%= notice %>
      </div>
    <% end %>

    <% if alert %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>